### ISSUE TITLE
Incorrect live

### ISSUE THREAD

**Issue by d-spiridonov** [FockinCorewar/Corewar#19]
Ячейки памяти, которые не соответствуют "сигнализированию процесса live" начинают светится так же как и те ячейки, которые сигнализируют. 
В функции void search_chmp производится присваивание флага для их подсветки. Необходимо проверить, почему некоторым другим ячейкам карты присваивается данный флаг. 
<img width="2363" alt="incorrect_live bug" src="https://user-images.githubusercontent.com/22715608/31704577-ae4cc260-b3ea-11e7-8677-18ef9ab2801c.png">

```
void search_chmp(t_skrr *skrr, int value, t_proc *process)
{
	t_chmp *chmp_tmp;

	chmp_tmp = skrr->chmp;
	while (chmp_tmp)
	{
		if (chmp_tmp->id == value)
		{
			chmp_tmp->last_live = g_cycles;
			chmp_tmp->live_count += 1;
			process->live_color = 1; //здесь включается флаг
			return ;
		}
		chmp_tmp = chmp_tmp->next;
	}
}
```

**Comment by ChoadPet** [comment]
Твой баг лил

**Comment by d-spiridonov** [comment]
fixed
